# Generated by Django 6.0.3 on 2026-03-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='generated_contend',
            new_name='generated_content',
        ),
    ]
